# Generated by Django 3.1.4 on 2020-12-24 21:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('release_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2020)])),
                ('company', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=512)),
                ('avg_rating', models.FloatField()),
            ],
        ),
    ]
