# Generated by Django 3.1.4 on 2020-12-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
    ]
